In [1]:
%matplotlib inline
from collections import defaultdict

import matplotlib.pylab as plt
from skimpy import skim
import numpy as np
import pandas as pd
from IPython.display import display, HTML
import seaborn as sns


In [2]:

import tensorflow as tf
import tensorflow_probability as tfp

from bayesianquilts.models.logistic_regression import LogisticRegression

2024-01-03 18:00:42.522874: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-03 18:00:42.548746: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-03 18:00:42.548772: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-03 18:00:42.549755: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-03 18:00:42.554491: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-03 18:00:42.554855: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [3]:
tf.__version__

'2.15.0'

In [4]:
tfp.__version__

'0.23.0'

# Load the dataset

Using the example from here: https://www.tensorflow.org/guide/core/logistic_regression_core

In [5]:
from ucimlrepo import fetch_ucirepo 


In [6]:
# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891) 
  
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features 
y = cdc_diabetes_health_indicators.data.targets 

In [15]:
X_scaled = (X - X.min())/X.max()
n = X_scaled.shape[0]
p = X_scaled.shape[1]

In [16]:
lr_model = LogisticRegression(dim_regressors=p, regression_interact=None)

In [17]:
lr_model.sample(1)

{'intercept__': <tf.Tensor: shape=(1, 1, 1), dtype=float64, numpy=array([[[0.00606185]]])>,
 'beta__': <tf.Tensor: shape=(1, 1, 21), dtype=float64, numpy=
 array([[[ 0.0112644 , -0.02000487, -0.01019887, -0.00386574,
          -0.00134389,  0.00517637, -0.00860098,  0.00071033,
          -0.01562623,  0.00162767, -0.01155714,  0.01747173,
           0.00244064, -0.00272712, -0.00218558,  0.00130492,
           0.00059278,  0.0183492 , -0.01033788,  0.01339786,
          -0.00924953]]])>}

In [18]:
batch_size = 3171

In [19]:
tfdata = tf.data.Dataset.from_tensor_slices({'X': X_scaled, 'y':y})

def data_factory():
    out = tfdata.shuffle(4000).batch(batch_size)
    return out

In [21]:
losses = lr_model.fit(
    data_factory,
    dataset_size=n,
    batches_per_epoch=int(n/batch_size),
    check_every=10,
    batch_size=200,
    num_epochs=500,
    max_decay_steps=400,
    max_plateau_epochs=100,
    sample_size=32,
    learning_rate=0.0015)

Saved a checkpoint: /tmp/tfcheckpoints/9fc88aaf-ae9c-47ad-bc76-dd653e82f9b3/9fc88aaf-ae9c-47ad-bc76-dd653e82f9b3-1


  0%|          | 0/100 [00:00<?, ?it/s]

TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'